# Generated by Django 5.2.2 on 2025-07-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('inventory', '0004_remove_ingredient_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
