# Generated by Django 5.2.2 on 2025-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOperationalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración Principal', max_length=100)),
                ('opening_time', models.TimeField(help_text='Hora de apertura del restaurante')),
                ('closing_time', models.TimeField(help_text='Hora de cierre del restaurante')),
                ('operational_cutoff_time', models.TimeField(default='05:00', help_text='Hora de corte para fecha operativa (por defecto 5:00 AM)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Operativa',
                'verbose_name_plural': 'Configuraciones Operativas',
                'db_table': 'restaurant_operational_config',
            },
        ),
    ]
