# Generated by Django 5.2.2 on 2025-08-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_add_container_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-id'], 'verbose_name': 'Envase', 'verbose_name_plural': 'Envases'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-id'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['-id'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
    ]