# Generated by Django 5.2.2 on 2025-08-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_model_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOperationalConfig',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
