# Generated by Django 5.2.2 on 2025-08-10 13:58
# Modified to handle missing tables gracefully

from django.db import migrations


def safe_noop(apps, schema_editor):
    """No operation - las tablas se limpiarán en 0012_safe_cleanup_old_models"""
    print("ℹ️  Migración 0011: Limpieza de modelos movida a migración posterior")


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_model_options'),
    ]

    operations = [
        # Reemplazado DeleteModel por RunPython para evitar errores
        migrations.RunPython(
            safe_noop,
            safe_noop,
            atomic=False
        ),
    ]
