# Generated by Django 5.2.2 on 2025-08-13 02:44

from django.db import migrations, connection


def safe_delete_models_if_exist(apps, schema_editor):
    """Eliminar modelos de forma segura solo si existen"""
    with connection.cursor() as cursor:
        try:
            # Eliminar tablas usando SQL directo con IF EXISTS
            cursor.execute('DROP TABLE IF EXISTS "config_restaurantoperationalconfig"')
            cursor.execute('DROP TABLE IF EXISTS "config_waiter"')
            print("✅ Modelos RestaurantOperationalConfig y Waiter eliminados (si existían)")
        except Exception as e:
            print(f"ℹ️  Error eliminando modelos: {e} - continuando...")


def reverse_safe_delete(apps, schema_editor):
    """Migración reversa: no hacer nada"""
    print("ℹ️  Migración reversa: no se requiere acción")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_safe_cleanup_old_models'),
    ]

    operations = [
        migrations.RunPython(
            safe_delete_models_if_exist,
            reverse_safe_delete,
            atomic=False  # No ejecutar en transacción para manejar errores mejor
        ),
    ]
