# Generated by Django 5.2.2 on 2025-08-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_safe_cleanup_old_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOperationalConfig',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
