# Generated by Django 5.2.2 on 2025-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('cocinero', 'Cocinero')], default='mesero', help_text='Rol del usuario en el restaurante', max_length=10),
        ),
    ]
