#!/bin/bash

# Deploy Frontend Fixes to EC2
# Script optimizado para deploy rápido solo del frontend

echo "🚀 DESPLEGANDO CORRECCIONES DE FRONTEND A EC2"
echo "=============================================="

# Variables
REPO_URL="https://github.com/guiEmotiv/restaurant-web.git"
EC2_HOST="ec2-3-145-167-239.us-east-2.compute.amazonaws.com"
PROJECT_DIR="/opt/restaurant-web"

# Instrucciones para EC2
echo ""
echo "📋 INSTRUCCIONES PARA EJECUTAR EN EC2:"
echo "======================================"
echo ""
echo "1. Conectarse a EC2:"
echo "   ssh -i restaurant-key.pem ec2-user@$EC2_HOST"
echo ""
echo "2. Ir al directorio del proyecto:"
echo "   cd $PROJECT_DIR"
echo ""
echo "3. Actualizar código desde repositorio:"
echo "   sudo git pull origin main"
echo ""
echo "4. Hacer deploy solo del frontend (más rápido):"
echo "   sudo ./deploy/build-deploy.sh --frontend-only"
echo ""
echo "   O si prefieres deploy completo:"
echo "   sudo ./deploy/build-deploy.sh"
echo ""
echo "5. Verificar que funcione:"
echo "   curl https://www.xn--elfogndedonsoto-zrb.com/api/v1/health/"
echo ""
echo "🔧 CAMBIOS INCLUIDOS EN ESTE DEPLOY:"
echo "===================================="
echo "✅ Corregir endpoint /operation/orders/ → /orders/ en TableStatus"
echo "✅ Cambiar PUT por POST add_item en TableOrderEcommerce"
echo "✅ Usar endpoint correcto /orders/{id}/add_item/ para agregar items"
echo "✅ Solucionar error al agregar items a órdenes existentes"
echo ""
echo "🎯 PROBLEMA SOLUCIONADO:"
echo "========================"
echo "El error al intentar agregar items a una orden existente desde"
echo "la vista de gestión de mesas ya está corregido."
echo ""
echo "📊 TIEMPO ESTIMADO:"
echo "==================="
echo "Frontend only: ~2-3 minutos"
echo "Deploy completo: ~5-8 minutos"
echo ""
echo "🔍 PARA VERIFICAR EL FIX:"
echo "========================="
echo "1. Ir a https://www.xn--elfogndedonsoto-zrb.com"
echo "2. Seleccionar una mesa con orden activa"
echo "3. Intentar agregar items - ya no debería dar error"
echo ""

# También mostrar los comandos para hacer local sync si es necesario
echo "💻 ALTERNATIVA - SYNC LOCAL AL EC2:"
echo "===================================="
echo "Si quieres subir directamente desde local:"
echo ""
echo "# Subir frontend compilado"
echo "scp -r -i restaurant-key.pem frontend/dist/* ec2-user@$EC2_HOST:$PROJECT_DIR/frontend/"
echo ""
echo "# Reiniciar contenedores"
echo "ssh -i restaurant-key.pem ec2-user@$EC2_HOST 'cd $PROJECT_DIR && sudo docker-compose -f docker-compose.simple.yml restart'"
echo ""

echo "✨ DEPLOY SCRIPT LISTO!"
echo "======================="