# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# RESTAURANT MANAGEMENT SYSTEM - OPTIMIZED DOCKER CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Two modes:
# 1. DEV:  Backend only - Frontend runs natively (npm run dev)
# 2. PROD: Complete stack with Nginx
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

services:
  # ────────────────────────────────────────────────────────────────────────
  # BACKEND SERVICE (Always used)
  # ────────────────────────────────────────────────────────────────────────
  app:
    build: .
    container_name: restaurant-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend  # Hot-reload for development
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings${PROD:+_ec2}
      - DATABASE_PATH=/app/data
      - DATABASE_NAME=restaurant_${PROD:+prod}${PROD:-dev}.sqlite3
    env_file:
      - .env.${PROD:+ec2}${PROD:-dev}
    restart: unless-stopped

  # ────────────────────────────────────────────────────────────────────────
  # NGINX SERVICE (Production only)
  # ────────────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: restaurant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    profiles:
      - production
    restart: unless-stopped