version: '3.8'

services:
  app:
    image: restaurant-web:latest
    container_name: restaurant-web-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/opt/restaurant-web/data
      - ./logs:/opt/restaurant-web/logs
    environment:
      - DATABASE_PATH=/opt/restaurant-web/data
      - DATABASE_NAME=restaurant_prod.sqlite3
    env_file:
      - .env.ec2
    restart: unless-stopped
    profiles:
      - production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: restaurant-web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./frontend-dist:/var/www/html:ro
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - production

volumes:
  restaurant_data:
    driver: local
  restaurant_logs:
    driver: local

networks:
  default:
    name: restaurant-network