# Generated by Django 5.2.2 on 2025-09-09 12:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Etiquetadora Mesa 1)', max_length=100)),
                ('usb_port', models.CharField(help_text='Puerto USB (ej: /dev/usb/lp0 o /dev/ttyUSB0)', max_length=100, unique=True)),
                ('device_path', models.CharField(blank=True, help_text='Ruta completa del dispositivo (auto-detectada)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retry_attempts', models.PositiveIntegerField(default=3, help_text='Intentos máximos de reimpresión')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, help_text='Timeout de conexión en segundos')),
                ('baud_rate', models.IntegerField(default=9600, help_text='Velocidad de comunicación (solo para seriales)')),
                ('paper_width_mm', models.IntegerField(default=80, help_text='Ancho del papel en mm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresora',
                'verbose_name_plural': 'Configuraciones de Impresoras',
                'db_table': 'printer_config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter', models.CharField(blank=True, help_text='Usuario que creó la orden', max_length=150, null=True, verbose_name='Mesero')),
                ('customer_name', models.CharField(default='Cliente', max_length=150, verbose_name='Nombre del cliente')),
                ('party_size', models.PositiveIntegerField(default=2, verbose_name='Cantidad de personas')),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'En Preparación'), ('SERVED', 'Servido'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.table')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ContainerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.container', verbose_name='Envase')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_sales', to='operation.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Venta de Envase',
                'verbose_name_plural': 'Ventas de Envases',
                'db_table': 'container_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'En Preparación'), ('SERVED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_takeaway', models.BooleanField(default=False, verbose_name='Para llevar')),
                ('has_taper', models.BooleanField(default=False, verbose_name='Con envoltorio')),
                ('container_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del envase al momento de la venta', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Impreso en cocina')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación')),
                ('container', models.ForeignKey(blank=True, help_text='Envase utilizado para este item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='config.container')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('YAPE_PLIN', 'Yape/Plin'), ('OTHER', 'Otro')], max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split_group', models.CharField(blank=True, max_length=36, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=100)),
                ('receipt_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Recibo impreso')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operation.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.orderitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='operation.payment')),
            ],
            options={
                'verbose_name': 'Item de Pago',
                'verbose_name_plural': 'Items de Pago',
                'db_table': 'payment_item',
                'unique_together': {('payment', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='PrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_content', models.TextField(verbose_name='Contenido de la etiqueta')),
                ('raw_data', models.TextField(blank=True, verbose_name='Datos ESC/POS procesados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'Imprimiendo'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('success_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True, verbose_name='Último error registrado')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.CharField(blank=True, help_text='Usuario que creó el trabajo', max_length=150)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='operation.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='operation.orderitem')),
                ('printer_config', models.ForeignKey(blank=True, help_text='Impresora asignada para este trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.printerconfig')),
            ],
            options={
                'verbose_name': 'Cola de Impresión',
                'verbose_name_plural': 'Cola de Impresión',
                'db_table': 'print_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='print_queue_status_8ff781_idx'), models.Index(fields=['printer_config', 'status'], name='print_queue_printer_115df2_idx'), models.Index(fields=['next_retry_at'], name='print_queue_next_re_01f680_idx')],
            },
        ),
    ]
