# Generated by Django 5.2.2 on 2025-09-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='print_confirmed',
            field=models.BooleanField(default=False, help_text='Confirmación de que la impresión fue exitosa'),
        ),
        migrations.DeleteModel(
            name='PrintQueue',
        ),
    ]
