# Generated by Django 5.2.2 on 2025-07-19 15:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Servido'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Servido'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
