# Generated by Django 5.2.2 on 2025-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_order_status_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('SERVED', 'Servido'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=10),
        ),
    ]
