# Generated by Django 5.2.2 on 2025-09-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_printerconfig_printqueue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printqueue',
            options={'ordering': ['created_at'], 'verbose_name': 'Cola de Impresión', 'verbose_name_plural': 'Cola de Impresión'},
        ),
        migrations.RemoveField(
            model_name='printqueue',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='printqueue',
            name='priority',
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='printer',
            field=models.ForeignKey(help_text='Impresora asignada', on_delete=django.db.models.deletion.CASCADE, to='operation.printerconfig'),
        ),
        migrations.AddIndex(
            model_name='printqueue',
            index=models.Index(fields=['printer', 'status'], name='print_queue_printer_9a78af_idx'),
        ),
    ]
