# Generated by Django 5.2.2 on 2025-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_priority_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerconfig',
            name='max_retry_attempts',
        ),
        migrations.RemoveField(
            model_name='printerconfig',
            name='timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='printqueue',
            name='current_attempts',
        ),
        migrations.RemoveField(
            model_name='printqueue',
            name='error_message',
        ),
        migrations.AddField(
            model_name='printqueue',
            name='status_message',
            field=models.TextField(blank=True, default='En cola para imprimir', help_text='Mensaje descriptivo del estado actual'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'Imprimiendo'), ('completed', 'Completado'), ('failed', 'Conexión perdida - Reintentará automáticamente'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='printqueue',
            index=models.Index(fields=['status', 'created_at'], name='print_queue_status_c93836_idx'),
        ),
    ]
