# Generated by Django 5.2.2 on 2025-07-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='preparing_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ready_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Entregado'), ('PAID', 'Pagado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Entregado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], max_length=10),
        ),
    ]
