# Generated by Django 5.2.2 on 2025-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_remove_order_cancelled_at_remove_order_ready_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('DELIVERY', 'Delivery')], default='RESTAURANT', help_text='Tipo de pedido: para consumo en restaurante o delivery', max_length=10),
        ),
    ]
