# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_simplify_print_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Etiquetadora Mesa 1)', max_length=100)),
                ('usb_port', models.CharField(help_text='Puerto USB (ej: /dev/usb/lp0 o /dev/ttyUSB0)', max_length=100, unique=True)),
                ('device_path', models.CharField(blank=True, help_text='Ruta completa del dispositivo (auto-detectada)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('baud_rate', models.IntegerField(default=9600, help_text='Velocidad de comunicación (solo para seriales)')),
                ('paper_width_mm', models.IntegerField(default=80, help_text='Ancho del papel en mm')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresora',
                'verbose_name_plural': 'Configuraciones de Impresoras',
                'db_table': 'printer_config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido ESC/POS para imprimir')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('printed', 'Impreso'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos de impresión')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Máximo número de intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error en caso de falla')),
                ('rpi_worker_id', models.CharField(blank=True, help_text='ID del worker RPi4 que procesa', max_length=100)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='operation.orderitem')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='operation.printerconfig')),
            ],
            options={
                'verbose_name': 'Trabajo de Impresión',
                'verbose_name_plural': 'Cola de Impresión',
                'db_table': 'print_queue',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['status', 'created_at'], name='print_queue_status_created_at_idx'),
                    models.Index(fields=['printer', 'status'], name='print_queue_printer_status_idx'),
                    models.Index(fields=['order_item'], name='print_queue_order_item_idx'),
                ],
            },
        ),
    ]