# Generated by Django 5.2.2 on 2025-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_create_printer_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='printqueue',
            new_name='print_queue_status_c93836_idx',
            old_name='print_queue_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='printqueue',
            new_name='print_queue_printer_9a78af_idx',
            old_name='print_queue_printer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='printqueue',
            new_name='print_queue_order_i_29b2ea_idx',
            old_name='print_queue_order_item_idx',
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se completó exitosamente', null=True),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='error_message',
            field=models.TextField(blank=True, help_text='Último mensaje de error'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se inició la impresión', null=True),
        ),
    ]
