# Generated by Django 5.2.2 on 2025-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_add_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
