# Generated by Django 5.2.2 on 2025-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_rename_print_queue_status_created_at_idx_print_queue_status_c93836_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'En Preparación'), ('PRINTED', 'Impreso'), ('SERVED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10),
        ),
    ]
