# Generated by Django 5.2.2 on 2025-07-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_remove_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operational_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='operational_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('YAPE_PLIN', 'Yape/Plin'), ('OTHER', 'Otro')], max_length=10),
        ),
    ]
