# Generated by Django 5.2.2 on 2025-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_add_container_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PAID', 'Pagado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.CharField(blank=True, help_text='Usuario que creó la orden', max_length=150, null=True, verbose_name='Mesero'),
        ),
    ]
