# Generated by Django 5.2.2 on 2025-08-09 06:31

from django.db import migrations
from django.db import connection


def check_and_remove_field(apps, schema_editor):
    """Safely remove operational_date field if it exists"""
    with connection.cursor() as cursor:
        # Check if the table and column exist
        cursor.execute("PRAGMA table_info(operation_order)")
        columns = [row[1] for row in cursor.fetchall()]
        if 'operational_date' in columns:
            cursor.execute("ALTER TABLE operation_order DROP COLUMN operational_date")


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_change_waiter_to_charfield'),
    ]

    operations = [
        migrations.RunPython(check_and_remove_field, migrations.RunPython.noop),
    ]
