# Generated by Django 5.2.2 on 2025-08-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_change_waiter_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operational_date',
        ),
    ]
