# Generated by Django 5.2.2 on 2025-08-10 13:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_create_cart_models'),
        ('inventory', '0008_alter_group_options_alter_ingredient_options_and_more'),
        ('operation', '0013_remove_order_operational_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containersale',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='operational_date',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único para la sesión del carrito', max_length=100, unique=True)),
                ('user', models.CharField(blank=True, help_text='Usuario/mesero que maneja el carrito', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del carrito (opcional)', null=True)),
                ('table', models.ForeignKey(help_text='Mesa asociada al carrito', on_delete=django.db.models.deletion.CASCADE, to='config.table')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'cart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de agregar al carrito', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, verbose_name='Notas especiales')),
                ('is_takeaway', models.BooleanField(default=False, verbose_name='Para llevar')),
                ('has_taper', models.BooleanField(default=False, verbose_name='Con envoltorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.cart')),
                ('container', models.ForeignKey(blank=True, help_text='Envase seleccionado si has_taper=True', null=True, on_delete=django.db.models.deletion.PROTECT, to='config.container')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'cart_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='cart_session_ab7233_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['table', 'updated_at'], name='cart_table_i_d5cc36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'recipe', 'notes', 'is_takeaway', 'has_taper', 'container')},
        ),
    ]
