# Generated by Django 5.2.2 on 2025-08-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_create_cart_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
