# Generated by Django 5.2.2 on 2025-08-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_safe_remove_operational_date_fields'),
    ]

    operations = [
        # Eliminar tablas Cart problemáticas
        migrations.RunSQL("DROP TABLE IF EXISTS cart_item;"),
        migrations.RunSQL("DROP TABLE IF EXISTS cart;"),
    ]
