# Generated by Django 5.2.2 on 2025-08-13 02:44
# Solo agregar campos a OrderItem

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_delete_restaurantoperationalconfig_delete_waiter'),
        ('operation', '0017_drop_cart_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Envase utilizado para este item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='config.container'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='container_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del envase al momento de la venta', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]