# Generated by Django 5.2.2 on 2025-08-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_add_preparing_status_to_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='container',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='containersale',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='operational_date',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='OrderItemIngredient',
        ),
    ]
