# Generated by Django 5.2.2 on 2025-08-17 05:14
# DISABLED: This migration fails in production because tables were already removed manually
# Use 0035_safe_cleanup_deprecated_tables.py instead

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_add_preparing_status_to_orderitem'),
    ]

    operations = [
        # Empty operations - tables cleanup handled by migration 0035
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
