# Generated by Django 5.2.2 on 2025-08-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_fix_dashboard_view_duplicates'),
    ]

    operations = [
        # Eliminar dashboard_financiero_view - ya no se usa, todo unificado en dashboard_operativo_view
        migrations.RunSQL(
            "DROP VIEW IF EXISTS dashboard_financiero_view;",
            reverse_sql=""
        ),
        
        # Eliminar índices relacionados
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_dashboard_financiero_operational_date;",
            reverse_sql=""
        ),
        
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_dashboard_financiero_category;",
            reverse_sql=""
        ),
        
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_dashboard_financiero_payment_method;",
            reverse_sql=""
        ),
    ]
