# Generated by Django 5.2.2 on 2025-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0036_recreate_dashboard_view_correct_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='container',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='containersale',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operational_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='operational_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='OrderItemIngredient',
        ),
    ]
