# Generated by Django 5.2.2 on 2025-09-02 16:57
# FIXED VERSION: Safe removal with existence checks for production deployment

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0036_recreate_dashboard_view_correct_tables'),
    ]

    operations = [
        # Safe operational date field removals using SQL (might not exist)
        migrations.RunSQL(
            "ALTER TABLE container_sale DROP COLUMN IF EXISTS operational_date;",
            reverse_sql="-- Cannot reverse this operation",
            hints={'safe_operation': True}
        ),
        
        migrations.RunSQL(
            "ALTER TABLE orders DROP COLUMN IF EXISTS operational_date;", 
            reverse_sql="-- Cannot reverse this operation",
            hints={'safe_operation': True}
        ),
        
        migrations.RunSQL(
            "ALTER TABLE payment DROP COLUMN IF EXISTS operational_date;",
            reverse_sql="-- Cannot reverse this operation", 
            hints={'safe_operation': True}
        ),
        
        # Add new Order fields (safe to add)
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
        
        # Safe table drops (only if they exist) - these were already dropped in 0017
        migrations.RunSQL(
            "DROP TABLE IF EXISTS cart;",
            reverse_sql="-- Cannot reverse this operation",
            hints={'safe_operation': True}
        ),
        
        migrations.RunSQL(
            "DROP TABLE IF EXISTS cart_item;", 
            reverse_sql="-- Cannot reverse this operation",
            hints={'safe_operation': True}
        ),
        
        migrations.RunSQL(
            "DROP TABLE IF EXISTS operation_orderitemingredient;",
            reverse_sql="-- Cannot reverse this operation",
            hints={'safe_operation': True}
        ),
    ]
