# Generated by Django 5.2.2 on 2025-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0037_remove_cartitem_cart_remove_cartitem_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
    ]
