# Generated by Django 5.2.2 on 2025-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0038_auto_20250902_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Cliente', max_length=150, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='party_size',
            field=models.PositiveIntegerField(default=2, verbose_name='Cantidad de personas'),
        ),
    ]
