# Generated by Django 5.2.2 on 2025-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0039_alter_order_customer_name_alter_order_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Servido'), ('PAID', 'Pagado')], default='CREATED', max_length=10),
        ),
    ]
