# Generated by Django 5.2.2 on 2025-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0040_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SERVED', 'Servido'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'En Preparación'), ('SERVED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10),
        ),
    ]
