# Generated by Django 5.2.2 on 2025-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0041_order_canceled_at_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('PREPARING', 'En Preparación'), ('SERVED', 'Servido'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=10),
        ),
    ]
