# Generated by Expert Software Architect on 2025-09-05
# MERGE MIGRATION: Resolves conflict between production integrity fixes and status updates

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0042_add_preparing_status'),
        ('operation', '0044_fix_production_data_integrity'),
    ]

    operations = [
        # This is a merge migration with no operations
        # It resolves the conflict between:
        # - 0038: Production database integrity fixes
        # - 0042: New PREPARING status and preparing_at field
    ]