# Generated by Django 5.2.2 on 2025-09-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0045_merge_production_fixes'),
        ('operation', '0046_fix_dashboard_view_table_names'),
    ]

    operations = [
    ]
