services:
  app:
    image: restaurant-app:fixed
    container_name: restaurant-web-app
    ports:
      - '8000:8000'
    volumes:
      - /opt/restaurant-web/data:/opt/restaurant-web/data
    env_file: 
      - /opt/restaurant-web/.env
    restart: unless-stopped
    profiles: [production]
    networks: [restaurant-network]
    # Temporarily disable healthcheck to isolate restart issue
    healthcheck:
      disable: true
    # Add resource limits to prevent OOM kills
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: restaurant-web-nginx
    ports: ['80:80', '443:443']
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on: [app]
    restart: unless-stopped
    profiles: [production]
    networks: [restaurant-network]

  certbot:
    image: certbot/certbot
    container_name: restaurant-web-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@xn--elfogndedonsoto-zrb.com --agree-tos --no-eff-email -d xn--elfogndedonsoto-zrb.com -d www.xn--elfogndedonsoto-zrb.com
    profiles: [ssl-setup]

networks:
  restaurant-network:
    driver: bridge
