# Generated by Django 5.2.2 on 2025-09-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Impresora asignada para esta receta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.printerconfig'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
