# Generated by Django 5.2.2 on 2025-07-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_group_description_remove_group_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
    ]
