# Generated by Django 5.2.2 on 2025-07-26 00:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ganancia sobre el costo de ingredientes', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
