# Generated by Django 5.2.2 on 2025-07-26 14:01

from django.db import migrations


def update_ingredients_active_status(apps, schema_editor):
    """Update is_active field based on current_stock"""
    Ingredient = apps.get_model('inventory', 'Ingredient')
    
    # Update all ingredients: active if stock > 0, inactive if stock = 0
    for ingredient in Ingredient.objects.all():
        ingredient.is_active = ingredient.current_stock > 0
        ingredient.save(update_fields=['is_active'])


def reverse_update_ingredients_active_status(apps, schema_editor):
    """Reverse migration - set all ingredients to active"""
    Ingredient = apps.get_model('inventory', 'Ingredient')
    Ingredient.objects.all().update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_profit_percentage_to_recipe'),
    ]

    operations = [
        migrations.RunPython(
            update_ingredients_active_status,
            reverse_update_ingredients_active_status
        ),
    ]
