# Generated by Django 5.2.2 on 2025-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_update_ingredients_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Solo las versiones activas se muestran al crear pedidos'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=models.CharField(default='1.0', help_text='Versión de la receta (ej: 1.0, 1.1, 2.0)', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'version')},
        ),
    ]
