# Generated by Django 5.2.2 on 2025-08-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_delete_restaurantoperationalconfig_delete_waiter_and_more'),
        ('inventory', '0007_recipe_is_active_recipe_version_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-id'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Envase recomendado para pedidos para llevar', null=True, on_delete=django.db.models.deletion.PROTECT, to='config.container'),
        ),
    ]
