name: Cleanup EC2 Environment

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      confirm:
        description: 'Type "CLEANUP" to confirm complete environment cleanup'
        required: true
        default: ''

env:
  AWS_REGION: us-west-2

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Clean EC2 Environment
    if: github.event.inputs.confirm == 'CLEANUP'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PROD_HOST }} >> ~/.ssh/known_hosts
        
    - name: Upload and execute cleanup script
      env:
        EC2_HOST: ${{ secrets.EC2_PROD_HOST }}
        EC2_USER: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "🚨 Starting COMPLETE EC2 ENVIRONMENT CLEANUP..."
        echo "⚠️  This will remove ALL containers, images, configs, and temp files"
        
        # Upload cleanup script
        scp -o StrictHostKeyChecking=no scripts/cleanup-ec2-environment.sh $EC2_USER@$EC2_HOST:/tmp/cleanup-ec2-environment.sh
        
        # Execute cleanup script
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'CLEANUP_SCRIPT'
        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
        
        chmod +x /tmp/cleanup-ec2-environment.sh
        /tmp/cleanup-ec2-environment.sh
        
        # Remove the script itself
        rm -f /tmp/cleanup-ec2-environment.sh
        CLEANUP_SCRIPT
        
    - name: Verify cleanup completion
      env:
        EC2_HOST: ${{ secrets.EC2_PROD_HOST }}
        EC2_USER: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "🔍 Verifying cleanup completion..."
        
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'VERIFY'
        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
        
        echo "=== Docker Status ==="
        docker ps -a || echo "No containers found (good)"
        echo ""
        docker images || echo "No images found (good)"
        echo ""
        
        echo "=== Directory Structure ==="
        cd /opt/restaurant-web
        ls -la
        echo ""
        
        echo "=== Nginx Configs ==="
        if [ -d nginx/conf.d ]; then
          ls -la nginx/conf.d/
        else
          echo "No nginx configs found"
        fi
        echo ""
        
        echo "=== Disk Usage ==="
        df -h /
        echo ""
        
        echo "✅ Environment cleanup verification completed"
        VERIFY