name: Deep EC2 Environment Inspection

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      analysis_level:
        description: 'Analysis depth (basic/detailed/full)'
        required: true
        default: 'detailed'
        type: choice
        options:
          - basic
          - detailed 
          - full

env:
  AWS_REGION: us-west-2

jobs:
  inspect:
    runs-on: ubuntu-latest
    name: Inspect EC2 Environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PROD_HOST }} >> ~/.ssh/known_hosts
        
    - name: Upload and execute inspection script
      env:
        EC2_HOST: ${{ secrets.EC2_PROD_HOST }}
        EC2_USER: ${{ secrets.EC2_USERNAME }}
        ANALYSIS_LEVEL: ${{ github.event.inputs.analysis_level }}
      run: |
        echo "🔍 Starting DEEP EC2 ENVIRONMENT INSPECTION..."
        echo "Analysis level: $ANALYSIS_LEVEL"
        
        # Upload inspection script
        scp -o StrictHostKeyChecking=no scripts/deep-inspection-ec2.sh $EC2_USER@$EC2_HOST:/tmp/deep-inspection-ec2.sh
        
        # Execute inspection script
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'INSPECT_SCRIPT'
        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
        
        chmod +x /tmp/deep-inspection-ec2.sh
        /tmp/deep-inspection-ec2.sh
        
        # Remove the script itself
        rm -f /tmp/deep-inspection-ec2.sh
        INSPECT_SCRIPT
        
    - name: Compare with local repository structure
      run: |
        echo ""
        echo "🏠 LOCAL REPOSITORY STRUCTURE FOR COMPARISON:"
        echo "============================================="
        echo ""
        echo "Local top-level structure:"
        ls -la
        echo ""
        echo "Local nginx configs:"
        if [ -d nginx/conf.d ]; then
          ls -la nginx/conf.d/
        else
          echo "No nginx/conf.d directory"
        fi
        echo ""
        echo "Local docker-compose.yml:"
        if [ -f docker-compose.yml ]; then
          echo "✓ Present"
          echo "Key services defined:"
          grep -E "^\s+[a-zA-Z].*:" docker-compose.yml | sed 's/://g' | sort
        else
          echo "✗ Missing"
        fi